# Permalinks
permalink:           pretty

# Setup
title:               J. Law. Cordova
description:         Create enterprise applications, backend systems, and automated pipelines with software developer J. Law. Cordova.
url:                 https://jlawcordova.com
paginate:            8
paginate_path:       "/blog/page:num/"
baseurl:             https://jlawcordova.com

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Junel Lawrence Cordova
  url:               https://twitter.com/jlawcordova
  github:            https://github.com/jlawcordova
  linkedin:          https://www.linkedin.com/in/jlawcordova
  twitter:           https://twitter.com/jlawcordova
  email:             jlaw.cordova@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jlawcordova

# Gems
gems: [jekyll-paginate, jekyll-gist]

plugins: [jekyll-paginate, jekyll-gist]
