# Permalinks
permalink:           pretty

# Setup
title:               jlawcordova
tagline:             Code and Create
url:                 https://jlawcordova.com
paginate:            1
baseurl:             https://jlawcordova.com

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Junel Lawrence Cordova
  url:               https://twitter.com/jlawcordova
  email:             jlaw.cordova@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jlawcordova

# Gems
gems: [jekyll-paginate, jekyll-gist]

plugins: [jekyll-paginate, jekyll-gist]
